/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Oscar.tugas2pbo;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author User
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();
        txtSuhu = new javax.swing.JTextField();
        cmbKonversi = new javax.swing.JComboBox<>();
        rdbCkeF = new javax.swing.JRadioButton();
        rdbFkeC = new javax.swing.JRadioButton();
        jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Masukan Suhu :");

        txtSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuhuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuhuKeyTyped(evt);
            }
        });

        cmbKonversi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius Ke Fahrenheit", "Fahrenheit ke Celcius" }));
        cmbKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKonversiActionPerformed(evt);
            }
        });

        rdbCkeF.setText("Celcius ke Fahrenheit");
        rdbCkeF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbCkeFItemStateChanged(evt);
            }
        });

        rdbFkeC.setText("Fahrenheit ke Celcius");
        rdbFkeC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbFkeCItemStateChanged(evt);
            }
        });

        jButton.setText("Konversi");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHasil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSuhu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton)
                        .addGap(10, 10, 10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(cmbKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbFkeC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbCkeF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHasil)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbCkeF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbFkeC)
                .addGap(18, 18, 18)
                .addComponent(jButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuhuKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // Batalkan input jika bukan angka atau titik desimal
        }
    }//GEN-LAST:event_txtSuhuKeyTyped

    private void rdbCkeFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbCkeFItemStateChanged
        if (rdbCkeF.isSelected()) {
            cmbKonversi.setSelectedItem("Celcius ke Fahrenheit");
        }
    }//GEN-LAST:event_rdbCkeFItemStateChanged

    private void rdbFkeCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbFkeCItemStateChanged
        if (rdbFkeC.isSelected()) {
            cmbKonversi.setSelectedItem("Fahrenheit ke Celcius");
        }
    }//GEN-LAST:event_rdbFkeCItemStateChanged

    private void txtSuhuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuhuKeyReleased
        jButtonActionPerformed(null);
    }//GEN-LAST:event_txtSuhuKeyReleased

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        try {
                    // Ambil nilai suhu dari JTextField
                    String input = txtSuhu.getText();
                    if (input.isEmpty()) {
                        throw new Exception("Masukkan nilai suhu!");
                    }
                    double suhu = Double.parseDouble(input);

                    // Ambil pilihan konversi dari JComboBox
                    String pilihan = (String) cmbKonversi.getSelectedItem();
                    double hasil = 0;

                    // Hitung hasil konversi berdasarkan pilihan
                    if ("Celcius ke Fahrenheit".equals(pilihan)) {
                        hasil = (suhu * 9 / 5) + 32;
                    } else if ("Celcius ke Kelvin".equals(pilihan)) {
                        hasil = suhu + 273.15;
                    } else if ("Fahrenheit ke Celcius".equals(pilihan)) {
                        hasil = (suhu - 32) * 5 / 9;
                    } else if ("Kelvin ke Celcius".equals(pilihan)) {
                        hasil = suhu - 273.15;
                    }

                    // Tampilkan hasil
                    lblHasil.setText("Hasil: " + hasil);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", 
                        "Error", JOptionPane.ERROR_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_jButtonActionPerformed

    private void cmbKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKonversiActionPerformed

    }//GEN-LAST:event_cmbKonversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbKonversi;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JRadioButton rdbCkeF;
    private javax.swing.JRadioButton rdbFkeC;
    private javax.swing.JTextField txtSuhu;
    // End of variables declaration//GEN-END:variables
}
